name: CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'VinylTool_UPLOAD/**'
      - '.github/workflows/ci.yml'

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install minimal deps (if any)
        run: |
          python -V
      - name: Static syntax check
        run: |
git ls-files -z 'VinylTool_UPLOAD/**/*.py' 'VinylTool_UPLOAD/*.py' | xargs -0 -r python -m py_compile
      - name: Smoketest (no secrets)
        run: |
          ./VinylTool_UPLOAD/scripts/deal_hunter_smoketest.py
